services:
  redis:
    image: redis:3.2
  web:
    build:
      context: ~/Desktop/docker/docker_compose/app/web
    depends_on:
    - redis
    ports:
    - 8001:80/tcp
    volumes:
    - ~/Desktop/docker/docker_compose/app/web:/web:rw
version: '3.0'
